### ISSUE TITLE
Minimum or maximum supported Node version?

### ISSUE THREAD

**Issue by kolohelios** [fuse-box/fuse-box-electron-seed#11]
I'm curious if there is a minimum or maximum supported Node version. I found I had to add async...await for "'build:main'" to get the Fuse dev server to start after the fuse.run() for spawning Electron. I'm happy to create a PR but only if there's an understanding that the supported Node version is a minimum of version 8. At this point, ≥ version 8 seems safe but I don't want to assume.

**Comment by nchanged** [comment]
@kolohelios that's correct! Node 8 it is ;-)

**Comment by kolohelios** [comment]
Upon further investigation, as least in Node.JS v10.13, it looks like we don't need the async handler. When stdio is set to "inherit", it seems to block the thread. Changing it to "pipe" allows the dev server to work again, as well as sets stdout and stderr to the proper child_process objects (with which we can reinstate the logging listeners).
