### ISSUE TITLE
Change nodeIntegration to false for security

### ISSUE THREAD

**Issue by proudust** [fuse-box/fuse-box-electron-seed#16]
Electron recommends that nodeIntegration be false and contextIsolation be true in [Electron Documentation](https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content).

**Comment by nchanged** [comment]
Will be changed with the upcoming version

**Comment by proudust** [comment]
> LIMITED SUPPORT. USE AT YOUR OWN RISK
> [fuse-box/fuse-box](https://github.com/fuse-box/fuse-box#limited-support-use-at-your-own-risk)

とのこと
